### ISSUE TITLE
Many to Many ref

### ISSUE THREAD

**Issue by Hydeo** [radzserg/rs-db-seeder#11]
Hi, 

Like your approach to the seeding problem. 
How would you handle a N-N relationship ? 

Using scenarios and calling those in your 'ref' ?

**Comment by radzserg** [comment]
Hi @Hydeo, 

You can use inline notation
```typescript
const user = await dbSeeder.insert("user");
const user = await dbSeeder.insertMany(2, "user_to_catalog", { user_id: 100 });
```

or can automate it via scenario. 

```typescript
seeder.addScenario({
    id: "userWithCatalogs",
    insert: async (
        storage: AdvancedKnexPgStorageWriter,
        data: any
    ): Promise<any> => {
        const user = await dbSeeder.insert("user");
        const user = await dbSeeder.insertMany(faker.datatype.number({min: 1, max: 3}), "user_to_catalog", { user_id: 100 });
    },
});
```

Considering that the user MUST belong to 1+ catalogs scenario looks like the best option. If a user can be inserted without a ref to catalog it's up to you.
